name: Prepare Git Report for Acts-Athena integration

on:
  workflow_dispatch:
    inputs:
      author:
        description: 'Author of the Git Report document'
        required: true
        default: 'Carlo Varni'
      date:
        description: 'Date of the report'
        required: true
      title:
        description: 'Title of the presentation'
        required: true
        default: 'Acts-Athena integration, MRs report'
      output_file:
        description: 'Name of the output latex file'
        required: true
        default: 'Report-Acts-Athena.tex'
      from_date:
        description: 'Get gitlab merge requests from given date'
        required: true
      to_date:
        description: 'Get gitlab merge requests up to given date'
        required: true
      branch:
        description: 'List of branches, comma separated'
        required: true
        default: 'master'
      labels:
        description: 'List of labels, comma separated'
        required: true
        default: 'ACTS'

jobs:
  prepare_git_report:
    name: Prepare Git Report
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.API_GITLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: install required packages
        run: |
          make
          
      - name: execute py script
        run: |
          make run PARAMS="--author '${{ github.event.inputs.author }}' --date '${{ github.event.inputs.date }}' --title '${{ github.event.inputs.title }}' --output_file '${{ github.event.inputs.output_file }}' --from_date '${{ github.event.inputs.from_date }}' --to_date '${{ github.event.inputs.to_date }}' --branch '${{ github.event.inputs.branch }}' --labels ${{ github.event.inputs.labels }}" 
      
      - name: clear
        run: |
          make clean
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: git-latex-report
          path: |
            *.tex

  prepare-pdf-report:
    name: Prepare PDF Report
    runs-on: ubuntu-latest
    needs: prepare_git_report

    steps:
      - name: Download artifacts from latex creation
        uses: actions/download-artifact@v3
        with:
          name: git-latex-report

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ github.event.inputs.output_file }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: git-pdf-report
          path: |
            *.pdf

